### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by NeoRUSSS** [Storik4pro/goodbyeDPI-UI#1]
![Error](https://github.com/user-attachments/assets/bcb9f0e5-76cf-468f-848f-249320b96019)

**Comment by NeoRUSSS** [comment]
Traceback (most recent call last):
  File "src\main.py", line 20, in <module>
  File "C:\Program Files\GoodbyeDPI_UI\_internal\utils.py", line 17, in <module>
    import winpty
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "winpty\__init__.py", line 10, in <module>
ImportError: DLL load failed while importing winpty: Не найдена указанная процедура.

**Comment by Storik4pro** [comment]
Здравствуйте!
Для решение проблемы мне необходима следующая информация о системе:

- Версия Windows (например, Windows 10 22H2)
- Разрядность системы (64bit/32bit)

Так же вы можете попробовать скачать пакет [Microsoft Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe), если он у вас не установлен

**Comment by NeoRUSSS** [comment]
Название ОС:                      Майкрософт Windows 10 Pro для рабочих станций
Версия ОС:                        10.0.17134 Н/Д построение 17134 X64

После обновления перестала запускаться

**Comment by Storik4pro** [comment]
Попробуйте переустановить goodbyeDPI UI. 
Если это не поможет, возможно стоит обновить Windows.
Так же антивирус может удалять некоторые зависимости, попробуйте его отключить во время переустановки программы

**Comment by NeoRUSSS** [comment]
Переустановка не помогает, антивирус отключен, до обновления работала исправно

**Comment by Storik4pro** [comment]
Какая версия программы работала исправно?

**Comment by NeoRUSSS** [comment]
Предыдущая

вт, 1 окт. 2024 г., 17:49 Storik4pro ***@***.***>:

**Comment by Storik4pro** [comment]
1.1.0?

**Comment by NeoRUSSS** [comment]
Да

вт, 1 окт. 2024 г., 17:59 Storik4pro ***@***.***>:

**Comment by Storik4pro** [comment]
Это странно, поскольку я не обновлял модуль, с которым произошла ошибка. Я займусь исследованием этой проблемы.
Пока что могу посоветовать следующее:  

- Скачайте версию 1.1.0 и пользуйтесь ей до выхода исправления
- Обновите Windows до версии 1809

Возможно, мне понадобится ваша помощь, если я не смогу повторить проблему, так что оставайтесь на связи

**Comment by NeoRUSSS** [comment]
Попробую завтра, т.к. машина рабочая виндовс обновить не смогу к сожалению.
На связи буду завтра днём

вт, 1 окт. 2024 г., 18:17 Storik4pro ***@***.***>:

**Comment by NeoRUSSS** [comment]
Все сделал, запустился, но - ютуб открылся но видео не воспроизводит, постоянно крутится колесо на черном экране, причем видео на миниатюрах воспроизводится.

**Comment by Storik4pro** [comment]
Похоже, что вам нужно подобрать параметры запуска вручную.
Следуйте этому [руководству](https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D1%81%D0%B5%D0%B3%D0%BE%D0%B4%D0%BD%D1%8F-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube/10529)
Учтите, что для добавлять параметры необходимо через запятую. Например: `--key, <value>,`

**Comment by Storik4pro** [comment]
Я постарался исправить эту проблему в последнем [обновлении 1.1.2](https://github.com/Storik4pro/goodbyeDPI-UI/releases/tag/1.1.2). Пожалуйста, установите его и дайте знать, решилась ли проблема

**Comment by NeoRUSSS** [comment]
Хорошо, спасибо, попробую

сб, 5 окт. 2024 г., 19:46 Storik4pro ***@***.***>:

**Comment by MRZS1** [comment]
![error](https://github.com/user-attachments/assets/3fed1f10-cb89-40a9-afda-0ed77760489e)
при запуске выдает ошибку

**Comment by Storik4pro** [comment]
> ![error](https://private-user-images.githubusercontent.com/192355821/397810404-3fed1f10-cb89-40a9-afda-0ed77760489e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MTQyNDgsIm5iZiI6MTczNDcxMzk0OCwicGF0aCI6Ii8xOTIzNTU4MjEvMzk3ODEwNDA0LTNmZWQxZjEwLWNiODktNDBhOS1hZmRhLTBlZDc3NzYwNDg5ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxNjU5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGUzODA1MGMxYThlOThlMWVkOTE5ZTI4ZDVjOTcxZmI3N2VmY2ZlNTgwOTQ5MmE1Y2UxNTllZDFiMTlhOTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mh4kn4DIkVaERG7yTyq8RCdgZjbqOsZbr-2j2tLZqwE) при запуске выдает ошибку

Попробуйте перезапустить компьютер

**Comment by perfecto1123** [comment]
![Image](https://github.com/user-attachments/assets/e2c77a71-3404-4253-a3f5-0a26fd8a8d5d)

**Comment by Storik4pro** [comment]
@perfecto1123, попробуйте остановить службу и запустить zapret снова
